name: Test, Build, and Deploy | Modul 01 - Lab2.2 Senior Project

on:
  push:
    branches: [main]

jobs:
  test-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Testing Build pre-Deploy
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm i
      - run: npm run build

  deploy:
   needs: test-build
     runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
       - name: Build app on VM
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USERNAME }}
           password: ${{ secrets.PASSWORD }}
           port: ${{ secrets.PORT}}
           script:
             eval "$(ssh-agent -s)"
             ssh-add ~/.ssh/senpro-ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH70sp16e7X+mHXcXo7A/f+EtlbXm3PJtinZFzU6tS3f seniorproject-rabu@seniorproject-rabu
             echo "Cek folder project";
             [ ! -d "/home/seniorproject-rabu/senpro/460560/modul01/senpro-github-action/" ] &&
               {
                 echo "Repository belum di-clone. Cloning...";
                 mkdir -p ~/senpro/460560/modul01;
                 cd ~/senpro/460560/modul01;
                 git clone git@github.com:Banendra17/senpro-github-action.git;
                 cd ~/senpro/460560/modul01/senpro-github-action;
                 echo "Install Package dan Build Project";
                 npm install;
                 npm run build;
               } ||
               {
                 echo "Repositorysudah ada. Building...";
                 cd ~/senpro/460560/modul01/senpro-github-action;
                 git restore .;
                 git pull origin main;
                 echo "Install Package dan Build Project";
                 npm install;
                 npm run build;
               } 



            